# Generated by Django 4.2.2 on 2023-09-29 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
