# Generated by Django 4.2.2 on 2023-09-29 17:26

from django.db import migrations, models
import polls.mycode


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_todoitem_date_and_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_and_time',
            field=models.DateTimeField(max_length=20, verbose_name=polls.mycode.get_time_date),
        ),
    ]
