# Generated by Django 4.2.2 on 2023-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_alter_todoitem_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote',
            field=models.IntegerField(auto_created=1, default=0),
            preserve_default=False,
        ),
    ]
