# Generated by Django 4.2.2 on 2023-09-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='candidate_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='candidate_state',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
