# Generated by Django 4.2.2 on 2023-10-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_priority', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
