# Generated by Django 4.2.2 on 2023-10-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtodo', '0002_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='task_priority',
        ),
        migrations.AddField(
            model_name='todolist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
