# Generated by Django 4.2.2 on 2023-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
