# Generated by Django 4.2.2 on 2023-10-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechteam', '0002_members_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
