# Generated by Django 4.2.2 on 2023-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechteam', '0003_members_joined_date_members_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='player_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
