# Generated by Django 4.2.2 on 2023-11-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptechteam', '0004_uploadedimage_members_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='player_image',
            field=models.ImageField(height_field=40, null=True, upload_to='', width_field=40),
        ),
    ]
