# Generated by Django 4.2.2 on 2023-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('course', models.CharField(choices=[('1', 'java'), ('2', 'python'), ('3', 'javascript')], max_length=15)),
            ],
        ),
    ]
